{% set name = "moleculekit" %}
{% set version = "1.8.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moleculekit-{{ version }}.tar.gz
  sha256: 3d377f5917a10309df2830ebb72ea804c97da7fc68453ae6d505e25a6ff6f8ed

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.18.5
    - cython >=0.29.21
    - toml
    - versioneer ==0.28
    - pip
  run:
    - numpy >=1.18.5
    - python
    - pandas >=1.1.2
    - networkx
    - tqdm
    - mmtf-python

test:
  imports:
    - moleculekit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Acellera/moleculekit
  summary: A molecule reading/writing and manipulation package.
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
