{% set name = "moleculekit" %}
{% set version = "1.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moleculekit-{{ version }}.tar.gz
  sha256: 067b5ff2e565484111e649c03a1b94367b26afb0804ca4218ac10dac301ee0f9

build:
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.18.5
    - cython >=0.29.21
    - toml
    - versioneer ==0.28
    - pip
  run:
    - msgpack-python
    - numpy >=1.18.5
    - python
    - pandas >=1.1.2
    - networkx
    - tqdm
    - mmtf-python

test:
  imports:
    - moleculekit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Acellera/moleculekit
  summary: A molecule reading/writing and manipulation package.
  license: OTHER
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefdoerr
    - jan-janssen
